### GET all prices with filters
GET {{baseUrl}}/{{apiV1Url}}/prices/prices/{{productId}}/{{brandId}}?pageSize=5&page=0

###
# Expected Response
# 200 OK
# Content-Type: application/json

### POST request with json body to get a price
GET {{baseUrl}}/{{apiV1Url}}/prices/price/{{productId}}/{{brandId}}/{{applicationDate}}

###
# Expected Response
# 200 OK
# Content-Type: application/json
